added env files to gitignore and minor updates in basic layout
the-canonizer/canonizer-3.0-frontend pull request #1
Opened 2022-01-13 11:01 UTC by shahab-ramzan

2022-01-18 17:25 UTC, akuks requested changes
There are conflicts with the development branch. Can you please check and fix the conflicts?

2022-01-19 08:04 UTC, shahab-ramzan commented
> There are conflicts with the development branch. Can you please check and fix the conflicts?

2022-01-19 08:05 UTC, shahab-ramzan commented
resolved conflicts. Please have a look and merge pull request

2022-01-20 12:46 UTC, akuks approved these changes

2022-01-20 12:46 UTC, merged