Can issue 1029
the-canonizer/canonizer-3.0-frontend pull request #1041
Opened 2023-05-19 07:50 UTC by shahab-ramzan

2023-05-29 07:43 UTC, akuks approved these changes

2023-05-29 07:44 UTC, akuks commented
@shahab-ramzan can you please resolve the conflict

2023-05-30 09:07 UTC, gautamv16 approved these changes

2023-05-30 09:08 UTC, gautamv16 requested changes
Resolve conflicts

2023-05-30 09:16 UTC, closed without merging