can-286
the-canonizer/canonizer-3.0-frontend pull request #1048
Opened 2023-05-22 11:37 UTC by shahab-ramzan

apply check when no event found

2023-05-29 07:45 UTC, akuks approved these changes

2023-05-29 07:46 UTC, akuks commented
@shahab-ramzan can you please resolve he conflicts

2023-05-30 08:34 UTC, gautamv16 approved these changes

2023-05-30 08:35 UTC, gautamv16 requested changes
PLease resolve conflicts

2023-05-31 04:38 UTC, akuks approved these changes

2023-05-31 04:38 UTC, merged