Fixes
the-canonizer/canonizer-3.0-frontend pull request #140
Opened 2022-05-10 11:40 UTC by ks-rahul

CAN-344,

2022-05-11 05:41 UTC, akuks requested changes

2022-05-11 05:41 UTC, akuks commented on src/network/api/campDetailApi.ts
> +    if (
Can we refactor this?

2022-05-11 05:48 UTC, ks-rahul commented on src/network/api/campDetailApi.ts
> +    if (
Done.

2022-05-12 06:12 UTC, akuks approved these changes

2022-05-12 06:12 UTC, merged