Can 515
the-canonizer/canonizer-3.0-frontend pull request #185
Opened 2022-05-25 14:24 UTC by shahab-ramzan

Add camp statement button added

2022-05-30 06:25 UTC, akuks requested changes

2022-05-30 06:25 UTC, akuks commented on src/components/ComponentPages/TopicDetails/CampStatementCard/index.tsx
> +                  ? "Manage/Edit Camp Statement"
Message must come from the common file

2022-05-30 06:25 UTC, akuks commented on src/components/ComponentPages/TopicDetails/index.tsx
> +              ? "Manage/Edit Camp Statement"
Message must come from the common file

2022-05-31 11:01 UTC, shahab-ramzan commented on src/components/ComponentPages/TopicDetails/CampStatementCard/index.tsx
> +                  ? "Manage/Edit Camp Statement"
Done

2022-06-01 05:13 UTC, akuks approved these changes

2022-06-01 05:13 UTC, merged