Can 614
the-canonizer/canonizer-3.0-frontend pull request #204
Opened 2022-06-01 14:52 UTC by shahab-ramzan

Add camp statement UI added

2022-06-03 04:56 UTC, akuks requested changes

2022-06-03 04:56 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +    if (isLogin) {
```javascript
(isLogin) ? nickNameListApiCall() : router.push("/login");
```

How about this?

2022-06-03 04:56 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +                              </Select.Option>
May be an array. Then iterate. I am pretty sure, we'll add more in this

2022-06-03 04:56 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +                                message: "Statement is required",
. Must come from a common message file

2022-06-03 04:56 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +                              message: "Edit summary is required",
. Must come from a common message file

2022-06-08 07:32 UTC, shahab-ramzan commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +    if (isLogin) {
Resolved in Next PR

2022-06-08 08:15 UTC, merged