can 642 and can 618
the-canonizer/canonizer-3.0-frontend pull request #260
Opened 2022-06-24 11:34 UTC by shahab-ramzan

Unit test cases

2022-06-27 03:27 UTC, akuks requested changes

2022-06-27 03:27 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/__test__/addOrManage.test.tsx
> +    const mainHeadig = screen.getByText(/statement update/i);
typo in `mainHeading`

2022-06-27 11:23 UTC, shahab-ramzan commented on src/components/ComponentPages/Statement/AddOrManage/__test__/addOrManage.test.tsx
> +    const mainHeadig = screen.getByText(/statement update/i);
Fixed

2022-06-28 03:03 UTC, akuks approved these changes

2022-06-28 03:03 UTC, merged