CAN-944
the-canonizer/canonizer-3.0-frontend pull request #319
Opened 2022-07-26 12:32 UTC by vikasranatalentelgia

Frontend implementaion for add delegate support

2022-07-27 08:26 UTC, akuks requested changes

2022-07-27 08:26 UTC, akuks commented on src/components/ComponentPages/CampForum/index.tsx
> +    console.log(
Dow we need this?

2022-07-28 05:11 UTC, vikasranatalentelgia commented on src/components/ComponentPages/CampForum/index.tsx
> +    console.log(
Removed

2022-07-29 07:56 UTC, akuks approved these changes

2022-07-29 07:56 UTC, merged