CAN-918
the-canonizer/canonizer-3.0-frontend pull request #384
Opened 2022-09-01 13:40 UTC by ks-rahul

1. CAN-1022
2. CAN-1024

2022-09-02 04:39 UTC, akuks requested changes

2022-09-02 04:39 UTC, akuks commented on src/components/ComponentPages/CreateNewCamp/index.tsx
> +    console.log("[ROOT]", roots);
Remove console.logs

2022-09-02 04:39 UTC, akuks commented on src/components/ComponentPages/CreateNewCamp/index.tsx
> +    for (i = 0; i < list.length; i += 1) {
for is repeated. Can we merge both?

2022-09-02 04:39 UTC, akuks commented on src/components/ComponentPages/CreateNewTopic/UI/FromUI.tsx
> +        // extra={
Remove the code if not required

2022-09-02 04:39 UTC, akuks commented on src/components/ComponentPages/CreateNewTopic/index.tsx
> +    // options.map((op) => (body[op.id] = op.checked ? 1 : 0));
Delete the commented code

2022-09-02 04:39 UTC, akuks commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +      // options.map((op) => (reqBody[op.id] = op.checked ? 1 : 0));
Delete the commented code

2022-09-02 04:39 UTC, akuks commented on src/utils/generalUtility.ts
> +    if (camp?.parent_camp_is_disabled === 1) {
Please refactor the nested ifs

2022-09-02 05:02 UTC, ks-rahul commented on src/components/ComponentPages/CreateNewCamp/index.tsx
> +    for (i = 0; i < list.length; i += 1) {
removed

2022-09-02 05:02 UTC, ks-rahul commented on src/components/ComponentPages/CreateNewCamp/index.tsx
> +    console.log("[ROOT]", roots);
removed

2022-09-02 05:05 UTC, ks-rahul commented on src/components/ComponentPages/CreateNewTopic/UI/FromUI.tsx
> +        // extra={
removed

2022-09-02 05:05 UTC, ks-rahul commented on src/components/ComponentPages/CreateNewTopic/index.tsx
> +    // options.map((op) => (body[op.id] = op.checked ? 1 : 0));
removed

2022-09-02 05:06 UTC, ks-rahul commented on src/components/ComponentPages/Statement/AddOrManage/index.tsx
> +      // options.map((op) => (reqBody[op.id] = op.checked ? 1 : 0));
deleted

2022-09-02 05:19 UTC, ks-rahul commented on src/utils/generalUtility.ts
> +    if (camp?.parent_camp_is_disabled === 1) {
refactored

2022-09-05 05:49 UTC, akuks approved these changes

2022-09-05 05:49 UTC, merged