Layout update
the-canonizer/canonizer-3.0-frontend pull request #40
Opened 2022-02-24 11:42 UTC by shahab-ramzan

tab icon added, networkcall code refactored, change header on user's log in/out

2022-02-24 13:22 UTC, akuks requested changes
Please go through the requested changes

2022-02-24 13:22 UTC, akuks commented on src/components/common/headContentAndPermisisonCheck/headContent.tsx
> +        href="https://canonizer.com/img/logo.png"
Probably put somewhere under the public folder. And then access it using the `BASE_URL/images/logo.png`. Moreover its pointing to old logo

2022-02-24 13:22 UTC, akuks commented on src/network/networkCall.ts
> +// import { message } from "antd";
Do we need this in future?

2022-02-24 13:22 UTC, akuks commented on src/network/networkCall.ts
> +          return (status >= 200 && status < 300) || status === 304;
Is there any status between 200 and 300?

2022-02-24 14:54 UTC, shahab-ramzan commented on src/components/common/headContentAndPermisisonCheck/headContent.tsx
> +        href="https://canonizer.com/img/logo.png"
Exactly, I already have tried. Need discussion on it

2022-02-25 14:32 UTC, akuks approved these changes

2022-02-25 14:32 UTC, merged