CAN-1159
the-canonizer/canonizer-3.0-frontend pull request #404
Opened 2022-09-13 10:29 UTC by ks-rahul

1. CAN-1159 fixed.

2022-09-14 03:05 UTC, akuks requested changes

2022-09-14 03:05 UTC, akuks commented on src/messages/validationRules.ts
> +    //     if (value && value?.trim().match(patterns.reg_email)) {
Please remove the commented code

2022-09-14 04:50 UTC, ks-rahul commented on src/messages/validationRules.ts
> +    //     if (value && value?.trim().match(patterns.reg_email)) {
removed

2022-09-15 05:11 UTC, akuks approved these changes

2022-09-15 05:11 UTC, merged