Fixes
the-canonizer/canonizer-3.0-frontend pull request #406
Opened 2022-09-14 13:08 UTC by vikasranatalentelgia

2022-09-15 05:13 UTC, akuks requested changes

2022-09-15 05:13 UTC, akuks commented on src/components/ComponentPages/CompareStatement/index.tsx
> +    console.log("ss", itemsStatus);
Please remove console logs

2022-09-15 11:42 UTC, vikasranatalentelgia commented on src/components/ComponentPages/CompareStatement/index.tsx
> +    console.log("ss", itemsStatus);
Removed

2022-09-16 04:09 UTC, akuks approved these changes

2022-09-16 04:09 UTC, merged