can-1077
the-canonizer/canonizer-3.0-frontend pull request #434
Opened 2022-09-26 11:16 UTC by shahab-ramzan

tooltip message for create new camp button updated

2022-09-27 05:47 UTC, akuks requested changes, later dismissed
Please do the changes

2022-09-28 13:51 UTC, shahab-ramzan commented
> Please do the changes

Done, Tooltip message moved to constant's file

2022-10-06 07:40 UTC, karun0607gautam submitted a review, later dismissed

2022-10-06 07:43 UTC, karun0607gautam approved these changes

2022-10-06 07:43 UTC, merged