Home page updates
the-canonizer/canonizer-3.0-frontend pull request #46
Opened 2022-02-28 11:43 UTC by shahab-ramzan

Added popover in topics list component, style updates in header and footer

2022-03-01 00:46 UTC, akuks requested changes

2022-03-01 00:46 UTC, akuks commented on package-lock.json
>    "version": "1.0.0",
Remove this file from commit.

2022-03-02 12:16 UTC, shahab-ramzan commented on package-lock.json
>    "version": "1.0.0",
removed

2022-03-02 13:04 UTC, akuks approved these changes

2022-03-02 13:05 UTC, merged