CAN-1317, CAN-1321
the-canonizer/canonizer-3.0-frontend pull request #470
Opened 2022-10-17 11:32 UTC by vikasranatalentelgia

Filed name on User profile must be uniform
Account Settings: UI issues
Support order issue

2022-10-18 03:44 UTC, akuks requested changes

2022-10-18 03:44 UTC, akuks commented on src/components/ComponentPages/UserProfile/UserProfileDetails/UserProfileCard.tsx
>                                            <a className={styles.Bluecolor}>
Aren't we using `<Link>` here?

2022-10-20 05:48 UTC, vikasranatalentelgia commented on src/components/ComponentPages/UserProfile/UserProfileDetails/UserProfileCard.tsx
>                                            <a className={styles.Bluecolor}>
Done

2022-10-25 12:44 UTC, akuks approved these changes

2022-10-25 12:44 UTC, merged