CAN-1366, 1414, 1454, 1463
the-canonizer/canonizer-3.0-frontend pull request #509
Opened 2022-11-09 10:49 UTC by ks-rahul

1. CAN-1366 fixed. 
2. CAN-1414fixed.
3. CAN-1454 fixed.
4. CAN-1463 fixed.

2022-11-09 13:35 UTC, akuks requested changes

2022-11-09 13:35 UTC, akuks commented on src/components/ComponentPages/ForgotPassword/__test__/forgotOTP.test.tsx
> +        "Note : OTP has been sent to your registered email address."
Must be from a common message file

2022-11-09 13:35 UTC, akuks commented on src/components/ComponentPages/SettingsUI/index.tsx
> +                Note : To change support order of camp, drag & drop the camp box on your choice position.
must be from common message file

2022-11-10 09:00 UTC, ks-rahul commented on src/components/ComponentPages/SettingsUI/index.tsx
> +                Note : To change support order of camp, drag & drop the camp box on your choice position.
moved

2022-11-10 09:01 UTC, ks-rahul commented on src/components/ComponentPages/ForgotPassword/__test__/forgotOTP.test.tsx
> +        "Note : OTP has been sent to your registered email address."
moved

2022-11-11 03:01 UTC, akuks approved these changes

2022-11-11 03:01 UTC, merged