#199, #868
the-canonizer/canonizer-3.0-frontend pull request #871
Opened 2023-03-15 09:52 UTC by ks-rahul

2023-03-17 04:56 UTC, gautamv16 submitted a review, later dismissed

2023-03-17 04:57 UTC, gautamv16 requested changes
Please  resolve conflicts

2023-03-17 05:14 UTC, ks-rahul commented
> Please resolve conflicts

resolved.

2023-03-20 04:04 UTC, akuks approved these changes

2023-03-20 04:05 UTC, merged